checkrunners:
- name: http
  plugin: github.com/frankh/norbert/checkrunners/http
  cron: "@every 10s"

  vars:
    expected: [200, 204]
    timeout: "15s"

# - name: http_auth
#   plugin: github.com/frankh/norbert/checkrunners/http
#   cron: "@every 2m"

#   vars:
#     expected: [401, 403]
#     timeout: "15s"

services:
- name: "Rocketboard"
  url: https://rocketboard.arachnys.com

checks:
- name: "HTTP Check"
  service: Rocketboard
  checkrunner: http
  severity: Info

  vars:
    url: https://rocketboard.arachnys.com/healthcheck
