checkrunners:
- name: http
  plugin: github.com/frankh/norbert/checkrunners/http

  vars:
    expected: [200, 204]
    timeout: "15s"
    interval: "2m"

- name: http_auth
  plugin: github.com/frankh/norbert/checkrunners/http

  vars:
    expected: [401, 403]
    timeout: "15s"
    interval: "2m"

services:
- name: "Rocketboard"
  url: https://rocketboard.arachnys.com

checks:
- name: "HTTP Check"
  service: Rocketboard
  checkrunner: http
  severity: Info

  vars:
    url: https://rocketboard.arachnys.com/healthcheck
