checkrunners:
- name: http
  plugin: github.com/frankh/norbert/checkrunners/http
  cron: "@every 10s"

  vars:
    expected: [200, 204]
    timeout: "15s"

- name: flaky
  plugin: github.com/frankh/norbert/checkrunners/flaky
  cron: "@every 10s"

  vars:
    successChance: 0.9
    failureChance: 0.5

# - name: http_auth
#   plugin: github.com/frankh/norbert/checkrunners/http
#   cron: "@every 2m"

#   vars:
#     expected: [401, 403]
#     timeout: "15s"

services:
- name: "Service 2"
  url: https://service.arachnys.com
- name: "Rocketboard"
  url: https://rocketboard.arachnys.com

checks:
- name: "HTTP Check"
  service: Rocketboard
  checkrunner: http
  severity: Info

  vars:
    url: https://rocketboard.arachnys.com/healthcheck

- name: "Flaky Check"
  service: Rocketboard
  checkrunner: flaky
  severity: Info

- name: "Flaky Check 2"
  service: Service 2
  checkrunner: flaky
  severity: Info
